// Regenerates lib/sourceBundle.ts (snapshot of the app source used by the download menu).
// Run: node scripts/gen-source.mjs   (after every code change, before building)
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const files = [];
const include = ['index.tsx', 'index.css', 'utils.ts', 'package.json', 'tsconfig.json', 'tailwind.preset.js', 'tokens.css'];
const dirs = ['components', 'finanzas', 'produccion', 'lib', 'types', 'scripts'];
const exts = /\.(tsx?|css|json|mjs|js)$/;
for (const f of include) if (fs.existsSync(path.join(root, f))) files.push(f);
const walk = (d) => { for (const e of fs.readdirSync(path.join(root, d), { withFileTypes: true })) {
  const p = `${d}/${e.name}`;
  if (e.isDirectory()) walk(p);
  else if (exts.test(e.name) && e.name !== 'sourceBundle.ts') files.push(p);
} };
dirs.forEach((d) => fs.existsSync(path.join(root, d)) && walk(d));
const out = Object.fromEntries(files.map((f) => [f, fs.readFileSync(path.join(root, f), 'utf8')]));
fs.writeFileSync(path.join(root, 'lib/sourceBundle.ts'),
  `// AUTO-GENERATED by scripts/gen-source.mjs — do not edit.\nexport const SOURCE_FILES: Record<string, string> = ${JSON.stringify(out)};\n`);
console.log(`${files.length} files`);
